package com.company;

public enum MenuPrintSelection {
    MAIN_MENU_SELECTION,
    SEND_TEXT_MESSAGE,
    MESSAGE_SENT,
    ENTER_NAME,
    ENTER_SURNAME,
    PERSON_EXIST,
    PROGRAM_EXIT_MESSAGE,
    ERROR_PRINT,
    MAIN_MENU_SELECTION_DEFAULT,
    NUMBER_CORRECT_MESSAGE,
    ERROR_MESSAGE_BOOK_EMPTY

}
